// swift-tools-version: 5.9
// This file is auto-generated by the release script.
// WARNING: Manual edits may be overwritten on the next release.

import PackageDescription

let package = Package(
    name: "NamiPairing",
    platforms: [
        .iOS(.v14),
        .macOS(.v10_15),
    ],
    products: [
        // Single public product: NamiPairing
        .library(
            name: "NamiPairing",
            targets: ["NamiPairingCore"]
        )
    ],
    dependencies: [
        .package(
            url: "https://github.com/airbnb/lottie-spm.git",
            .upToNextMajor(from: "4.4.3")
        )
    ],
    targets: [
        // Binary XCFramework with all core functionality.
        .binaryTarget(
            name: "NamiPairingFramework",
            url: "https://github.com/namiai/NamiPairing_iOS_thin/releases/download/5.0.0/NamiPairingFramework.xcframework.zip",
            checksum: "fc8487e752a9964ced2d104ce653df1af1984fa945a344cfa823bd3d4ae6e655"
        ),
        // Thin Swift wrapper target used by clients.
        .target(
            name: "NamiPairingCore",
            dependencies: [
                "NamiPairingFramework",
                .product(name: "Lottie", package: "lottie-spm")
            ],
            path: "Sources/NamiPairing/NamiPairingCore"
        )
    ]
)
