// swift-tools-version: 6.1
// This file is auto-generated by the release script.
// WARNING: Manual edits may be overwritten on the next release.

import PackageDescription

let package = Package(
    name: "NamiPairing",
    platforms: [
        .iOS(.v14),
        .macOS(.v10_15),
    ],
    products: [
        .library(
            name: "NamiPairing",
            targets: ["NamiPairingCore"]
        )
    ],
    dependencies: [
        .package(
            url: "https://github.com/airbnb/lottie-spm.git",
            .upToNextMajor(from: "4.4.3")
        )
    ],
    targets: [
        .binaryTarget(
            name: "NamiPairingFramework",
            url: "https://github.com/namiai/NamiPairing_iOS_thin/releases/download/5.3.2/NamiPairingFramework.xcframework.zip",
            checksum: "924b076d56216afc0e8434e97bf96f5b0d2194b1cfd431cc7fc9f3ad0d53704b"
        ),
        .target(
            name: "NamiPairingCore",
            dependencies: [
                "NamiPairingFramework",
                .product(name: "Lottie", package: "lottie-spm")
            ],
            path: "Sources/NamiPairing/NamiPairingCore"
        )
    ]
)
