// swift-tools-version: 5.10
// This file is auto-generated by the release script.
// WARNING: Manual edits may be overwritten on the next release.

import PackageDescription

let package = Package(
    name: "NamiPairing",
    platforms: [
        .iOS(.v14),
        .macOS(.v10_15),
    ],
    products: [
        .library(
            name: "NamiPairing",
            targets: ["NamiPairingCore"]
        )
    ],
    dependencies: [
        .package(
            url: "https://github.com/airbnb/lottie-spm.git",
            .upToNextMajor(from: "4.4.3")
        )
    ],
    targets: [
        .binaryTarget(
            name: "NamiPairingFramework",
            url: "https://github.com/namiai/NamiPairing_iOS_thin/releases/download/5.1.0/NamiPairingFramework.xcframework.zip",
            checksum: "5bf5f70d9267fd541a9d763f0be6769d52df49eeccce9184fe5648577ebd3831"
        ),
        .target(
            name: "NamiPairingCore",
            dependencies: [
                "NamiPairingFramework",
                .product(name: "Lottie", package: "lottie-spm")
            ],
            path: "Sources/NamiPairing/NamiPairingCore"
        )
    ]
)
